### ISSUE TITLE
Compatibility with Member version

### ISSUE THREAD

**Issue by MadeByIToncek** [AstronomyLiveYt/SatTraker#7]
Hello, I'm thinking about purchasing membership on your channel but I have one question. If I can connect my scope to this version of SatTraker (public one), will I be 100% capable to connect it with the member version? Are there any changes or the piblic version just lacks a lot of cool features and the telescope part is basically unchanged? Thanks for reply, if it is possible and the test goes well, you will surely have a membership from me 😉.

**Comment by mconsidine** [comment]
Hi,
I have the same question.  Did you ever get an answer?
Mconsidine
